services:
  web:
    build: .
    container_name: drf_web
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    expose:
      - 8000
    env_file:
      - .env
    # depends_on:
    #   - db   <-- bu qatorni o'chiring, SQLite3 uchun kerak emas

  nginx:
    image: nginx:latest
    container_name: drf_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/static
    depends_on:
      - web

volumes:
  static_volume:
